name: 'QASE Test Results Upload'
description: 'Uploads test case results to QASE.'
inputs:
  xml_file_path:
    description: 'Path to the XML file containing test case data.'
    required: true
  qase_token:
    description: 'QASE API token.'
    required: true
runs:
  using: 'docker'
  image: 'ghcr.io/data443/test_results_uploader:latest'  # Corrected image name
  env:
    QASE_TOKEN: ${{ inputs.qase_token }}  # Use the qase_token input as the environment variable
