name: 'QASE Test Results Upload'
description: 'Uploads test case results to QASE.'
inputs:
  xml_file_path:
    description: 'Path to the XML file containing test case data.'
    required: true
runs:
  using: 'docker'
  image: ${{ env.docker_image_name }}:${{ env.GitVersion_SemVer }}
  env:
    QASE_TOKEN: 78a635c4491dd8c825e184a5811f1d07fc13212500532da9e69e1fd4337b96ad
