name: 'QASE Test Results Upload'
description: 'Uploads test case results to QASE.'
inputs:
  xml_file_path:
    description: 'Path to the XML file containing test case data.'
    required: true
  qase_token:
    description: 'QASE API token.'
    required: true
runs:
  using: 'docker'
  image: 'ghcr.io/data443/test_results_uploader:latest'
  env:
    QASE_TOKEN: ${{ inputs.qase_token }}
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run QASE Test Results Upload
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app \
        -e QASE_TOKEN=${{ inputs.qase_token }} \
        python main.py ${{ inputs.xml_file_path }} ${{ inputs.qase_token }}
